Removed unused env variables, re-indent some stuff

diff --git a/home/.bash/aliases b/home/.bash/aliases
--- a/home/.bash/aliases
+++ b/home/.bash/aliases
@@ -20,7 +20,7 @@ done
 # Tomcat
 alias tc='catalina.sh run'
 
-#MySQL
+# MySQL
 alias my='mysql5'
 
 # MacPorts
@@ -43,11 +43,11 @@ alias reload='source ~/.bash_profile'
 
 # Quicker cd
 alias ..="cd .."
-alias cg='cd /Library/Ruby/Gems/1.8/gems/'
 function cr() {
  cd ~/repos/$*
 }
 
+# My Code folder
 function k() {
  cd ~/Code/$*
 }
@@ -73,34 +73,34 @@ alias lt='ls -lt' # sort with recently modified first
 alias md='mkdir -p'
 alias s='cd ..'   # up one dir
 
-#Changes JAVA_HOME env variable
+# Changes JAVA_HOME env variable
 function java_v() {
 	export JAVA_HOME="/System/Library/Frameworks/JavaVM.framework/Versions/$1/Home"
 }
 
-function take() { 
+function take() {
     mkdir -p "$1"
     cd "$1" 
 }
 
 alias e='exit'
 alias k9="killall -9"
-function killnamed () { 
-    ps ax | grep $1 | cut -d ' ' -f 2 | xargs kill 
+function killnamed () {
+	ps ax | grep $1 | cut -d ' ' -f 2 | xargs kill
 }
+
 function zipr() {
-  zip -r $1.zip $1
+	zip -r $1.zip $1
 }
 
 # Finder
 alias o='open . &'
-alias ff='open -a Firefox'
 
 # General code
 
 # From Chris Wanstrath
-function pless() { 
-    pygmentize $1 | less -r 
+function pless() {
+	pygmentize $1 | less -r
 }
 
 # Processes
@@ -113,10 +113,12 @@ alias gb='git branch'
 alias gba='git branch -a'
 alias gc='git commit -v'
 alias gca='git commit -v -a'
+
 # Commit pending changes and quote all args as message
 function gg() { 
-    git commit -v -a -m "$*"
+	git commit -v -a -m "$*"
 }
+
 alias gco='git checkout'
 alias gd='git diff'
 alias gdm='git diff master'
@@ -127,37 +129,34 @@ alias gst='git status'
 alias gt='git status'
 alias g='git status'
 alias eg='mate .git/config'
+
 # Git clone from GitHub
 function gch() {
-  git clone git://github.com/$USER/$1.git
+	git clone git://github.com/$USER/$1.git
 }
 
 # Setup a tracking branch from [remote] [branch_name]
 function gbt() { 
-  git branch --track $2 $1/$2 && git checkout $2 
+	git branch --track $2 $1/$2 && git checkout $2
 }
+
 # Quickly clobber a file and checkout
 function grf() { 
-  rm $1
-  git checkout $1 
+	rm $1
+	git checkout $1 
 }
 
 # Regenerate TAGS file from file arguments
 function ct() {
-  rm -f TAGS
-  etags --append --output=TAGS $*
+	rm -f TAGS
+	etags --append --output=TAGS $*
 }
-
-# TextMate
-alias et="mate"
-alias ett="mate ."
-alias etr="mate app config lib db schema public spec test vendor/gems vendor/plugins Rakefile Capfile Vladfile Todofile README stories merb slices tasks features &"
 
 # Ruby
 alias r="rake"
 
 function markdown() { 
-/Applications/TextMate.app/Contents/SharedSupport/Support/bin/Markdown.pl $1 > $1.html 
+	/Applications/TextMate.app/Contents/SharedSupport/Support/bin/Markdown.pl $1 > $1.html
 }
 
 # Rails
@@ -171,68 +170,40 @@ alias ss='./script/server'
 alias tl='tail -f log/*.log'
 alias ts='thin start'
 
-
-# XCode
-# Analyze release build
-alias sx="xcodebuild clean && ~/src/checker-0.146/scan-build -k -V xcodebuild"
-# Analyze test build
-alias sxt="xcodebuild -target Test clean && ~/src/checker-0.146/scan-build -k -V xcodebuild -target Test"
-# Call with -target Foo
-function sxx() { 
-  xcodebuild $* clean && ~/src/checker-0.146/scan-build -k -V xcodebuild $* 
-}
-
-alias ox="open *.xcodeproj"
-
-# Nginx
-function nginx_stop() {
-    ps ax | grep nginx | cut -d " " -f 1 | xargs sudo kill -9
-}
-function nginx_start() {
-    sudo /opt/nginx/sbin/nginx
-}
-
-# TaskPaper
-function new-tp() {
-    touch $1.taskpaper
-    open $1.taskpaper
-}
-
-
 # From http://github.com/suztomo/dotfiles
 function rmf(){
-    for file in $*
-    do
-        __rm_single_file $file
-    done
+	for file in $*
+	do
+		__rm_single_file $file
+	done
 }
 
 function __rm_single_file(){
-    if ! [ -d ~/.Trash/ ]
-    then
-        command /bin/mkdir ~/.Trash
-    fi
+	if ! [ -d ~/.Trash/ ]
+	then
+		command /bin/mkdir ~/.Trash
+	fi
 
-    if ! [ $# -eq 1 ]
-    then
-        echo "__rm_single_file: 1 argument required but $# passed."
-        exit
-    fi
+	if ! [ $# -eq 1 ]
+	then
+		echo "__rm_single_file: 1 argument required but $# passed."
+		exit
+	fi
 
-    if [ -e $1 ]
-    then
-        BASENAME=`basename $1`
-        NAME=$BASENAME
-        COUNT=0
-        while [ -e ~/.Trash/$NAME ]
-        do
-            COUNT=$(($COUNT+1))
-            NAME="$BASENAME.$COUNT"
-        done
+	if [ -e $1 ]
+	then
+		BASENAME=`basename $1`
+		NAME=$BASENAME
+		COUNT=0
+		while [ -e ~/.Trash/$NAME ]
+		do
+			COUNT=$(($COUNT+1))
+			NAME="$BASENAME.$COUNT"
+		done
 
-        command /bin/mv $1 ~/.Trash/$NAME
-    else
-        echo "No such file or directory: $file"
-    fi
+		command /bin/mv $1 ~/.Trash/$NAME
+	else
+		echo "No such file or directory: $file"
+	fi
 }
 
